#!/bin/sh

set -e 

if [ -z "$1" -o -z "$2" ]
then
	echo "usage: $0 <size> <file>"
	exit 1
fi

# echo $1 $2
swapsize="$1"
swapname="$2"


if [ -e $swapname ]
then
	echo "error: File already exists. $swapname"
	exit 1
fi

swapfile=$(losetup -f) #free loop device

# set NOCOW
touch $swapname
chattr +C $swapname
head -c $swapsize /dev/zero >> $swapname

losetup $swapfile $swapname #mount file to loop
mkswap  $swapfile
swapon  $swapfile
